-- 데이터 베이스 생성
CREATE DATABASE IF NOT EXISTS schedule;
USE schedule;

CREATE TABLE IF NOT EXISTS Schedule (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '일정 식별자',
    author VARCHAR(100) NOT NULL COMMENT '작성자',
    password VARCHAR(100) NOT NULL COMMENT '비밀번호',
    task VARCHAR(255) NOT NULL COMMENT '일정',
    createdDate DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성 날짜',
    updatedDate DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 날짜'
);